apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: hw-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: v2.1.0
  name: hw-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 300s
    scrapeTimeout: 180s
    port: hw-metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: hw-exporter
