apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: hw-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: v2.1.0
    prometheus: k8s
    role: alert-rules
  name: hw-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: hw-exporter
    rules:
    - alert: NodeFileDescriptorLimit
      annotations:
        description: File descriptors limit at {{ $labels.instance }} is currently at {{ printf "%.2f" $value }}%.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/hw/nodefiledescriptorlimit
        summary: Kernel is predicted to exhaust file descriptors limit soon.
      expr: |
        (
          node_filefd_allocated{job="hw-exporter"} * 100 / node_filefd_maximum{job="hw-exporter"} > 70
        )
      for: 15m
      labels:
        severity: warning
    - alert: NodeFileDescriptorLimit
      annotations:
        description: File descriptors limit at {{ $labels.instance }} is currently at {{ printf "%.2f" $value }}%.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/hw/nodefiledescriptorlimit
        summary: Kernel is predicted to exhaust file descriptors limit soon.
      expr: |
        (
          node_filefd_allocated{job="hw-exporter"} * 100 / node_filefd_maximum{job="hw-exporter"} > 90
        )
      for: 15m
      labels:
        severity: critical
  - name: hw-exporter.rules
    rules:
    - expr: |
        count without (cpu) (
          count without (mode) (
            node_cpu_seconds_total{job="hw-exporter"}
          )
        )
      record: instance:node_num_cpu:sum
    - expr: |
        1 - avg without (cpu, mode) (
          rate(node_cpu_seconds_total{job="hw-exporter", mode="idle"}[5m])
        )
      record: instance:node_cpu_utilisation:rate5m
    - expr: |
        (
          node_load1{job="hw-exporter"}
        /
          instance:node_num_cpu:sum{job="hw-exporter"}
        )
      record: instance:node_load1_per_cpu:ratio
