apiVersion: v1
kind: Secret
metadata:
  name: hw-exporter-config
  namespace: monitoring
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
stringData:
  config.ini: |
    [servers]
    csy-pm-eis-wuyingying-001=10.251.136.30@cmss@ceshi@cmss@Mima94g8z@
    csy-pm-eis-wuyingying-002=10.251.136.31@cmss@ceshi@cmss@Mima94g8z@
    csy-pm-eis-wuyingying-003=10.251.136.32@cmss@ceshi@cmss@Mima94g8z@
    csy-pm-eis-wuyingying-004=10.251.136.33@cmss@ceshi@cmss@Mima94g8z@